title: Jeff Anthony's Homepage
description: Bookmark this to keep track of what I'm doing

remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

layout: page
title: "CURRENT PROJECTS"
permalink: https://jeffanthony.github.io/currentProjects.md